# Generated by Django 2.0.3 on 2018-04-20 09:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('revoked_on', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['privilege__name'],
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(through='consent.Consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consent',
            name='privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consent.Privilege'),
        ),
        migrations.AddField(
            model_name='consent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('user', 'privilege')},
        ),
    ]
