# Generated by Django 2.0.3 on 2018-05-21 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_on', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
                'ordering': ['privilege__name'],
                'default_related_name': 'consents',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(related_name='privileges', through='consent.Consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privilege',
                'verbose_name_plural': 'privileges',
                'ordering': ['name'],
                'default_related_name': 'privileges',
            },
        ),
        migrations.AddField(
            model_name='consent',
            name='privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='consent.Privilege'),
        ),
        migrations.AddField(
            model_name='consent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('user', 'privilege')},
        ),
    ]
