# Generated by Django 2.0.3 on 2018-05-23 11:54

from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion


def migrate_users_to_ctype(apps, schema_editor):
    User = get_user_model()
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Consent = apps.get_model('consent', 'Consent')

    user_ctype = ContentType.objects.get_for_model(User)

    for consent in Consent.objects.all():
        consent.granter_ctype = user_ctype
        consent.granter_id = consent.user_id
        consent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='users',
        ),
        migrations.AddField(
            model_name='consent',
            name='granter_ctype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consent',
            name='granter_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('granter_ctype', 'granter_id', 'privilege')},
        ),
        migrations.RunPython(migrate_users_to_ctype),
        migrations.RemoveField(
            model_name='consent',
            name='user',
        ),
    ]
