# Generated by Django 2.0.4 on 2018-04-26 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consent',
            options={'ordering': ['privilege__name'], 'verbose_name': 'consent', 'verbose_name_plural': 'consents'},
        ),
        migrations.AlterModelOptions(
            name='privilege',
            options={'ordering': ['name'], 'verbose_name': 'privilege', 'verbose_name_plural': 'privileges'},
        ),
        migrations.AlterField(
            model_name='consent',
            name='granted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consent',
            name='privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='consent.Privilege'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='users',
            field=models.ManyToManyField(related_name='privileges', through='consent.Consent', to=settings.AUTH_USER_MODEL),
        ),
    ]
