# Generated by Django 2.0.4 on 2018-04-26 11:06

from django.db import migrations, models
from django.contrib.auth import get_user_model
import django.db.models.deletion


def users_to_content_types(apps, schema_editor):
    User = get_user_model()
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Consent = apps.get_model('consent', 'Consent')
    user_ctype = ContentType.objects.get_for_model(User)
    for consent in Consent.objects.all():
        consent.content_type = user_ctype
        consent.object_id = consent.user_id
        consent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('consent', '0002_auto_20180426_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consents', to='contenttypes.ContentType')
        ),
        migrations.AddField(
            model_name='consent',
            name='object_id',
            field=models.PositiveIntegerField()
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('content_type', 'object_id', 'privilege')},
        ),
        migrations.RunPython(users_to_content_types),
        migrations.RemoveField(
            model_name='privilege',
            name='users',
        ),
        migrations.RemoveField(
            model_name='consent',
            name='user',
        ),
    ]
