# Generated by Django 2.0.4 on 2018-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_auto_20180426_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='notes',
            field=models.TextField(blank=True, help_text='You can use this to keep notes of how the consent was granted, such as the actual text that was used to ask for consent.'),
        ),
    ]
